---
blueprint:
  name: Bathroom Fan Control
  description: Controls bathroom fan with timer and humidity management
  domain: automation
  input:
    fan_entity:
      name: Fan or Switch
      description: Select the fan or switch to control
      selector:
        entity:
          domain:
            - fan
            - switch
    humidity_sensor:
      name: Humidity Sensor
      selector:
        entity:
          domain: sensor
          device_class: humidity
    minimum_run_time:
      name: Minimum Run Time
      description: "Minimum time in minutes the fan should run"
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: "minutes"
    humidity_threshold:
      name: Humidity Threshold
      description: "Humidity percentage that triggers the fan"
      default: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

trigger:
  # Manual turn on trigger
  - platform: state
    entity_id: !input fan_entity
    to: "on"
    id: "manual_on"

  # High humidity trigger
  - platform: numeric_state
    entity_id: !input humidity_sensor
    above: !input humidity_threshold
    id: "humidity_high"

  # Low humidity trigger
  - platform: numeric_state
    entity_id: !input humidity_sensor
    below: !input humidity_threshold
    id: "humidity_low"

action:
  - variables:
      trigger_source: "{{ trigger.id }}"

  - choose:
      # Handle manual turn on
      - conditions: "{{ trigger_source == 'manual_on' }}"
        sequence:
          - delay:
              minutes: !input minimum_run_time
          - if:
              - condition: numeric_state
                entity_id: !input humidity_sensor
                below: !input humidity_threshold
            then:
              - service: homeassistant.turn_off
                target:
                  entity_id: !input fan_entity

      # Handle high humidity
      - conditions:
          - "{{ trigger_source == 'humidity_high' }}"
          - condition: state
            entity_id: !input fan_entity
            state: "off"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input fan_entity

      # Handle low humidity
      - conditions:
          - "{{ trigger_source == 'humidity_low' }}"
        sequence:
          - delay:
              minutes: !input minimum_run_time
          - service: homeassistant.turn_off
            target:
              entity_id: !input fan_entity

mode: restart
