blueprint:
  name: "Advanced Motion and Door Lighting Control with Late Night Mode"
  description: "Control lights based on motion and door sensors with sun-based schedule, late night options, and override switches"
  domain: automation
  input:
    motion_sensors:
      name: Motion Sensors
      description: "Select one or more motion sensors"
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true
    door_sensors:
      name: Door Sensors
      description: "Optional door sensors that will also trigger lights"
      selector:
        entity:
          domain: binary_sensor
          device_class: door
          multiple: true
    controlled_entities:
      name: Controlled Entities
      description: "Lights or scenes to be controlled"
      selector:
        target:
          entity:
            domain:
              - light
              - scene
              - switch
    override_input_boolean:
      name: Override Switch
      description: "Input boolean to disable motion/door control"
      selector:
        entity:
          domain: input_boolean
    sun_entity:
      name: Sun Entity
      description: "Entity to check for day/night"
      selector:
        entity:
          domain: sun
      default: sun.sun
    debug_mode:
      name: Debug Mode
      description: "Enable debug logging"
      selector:
        boolean:
      default: false
    no_motion_wait:
      name: Turn Off Delay
      description: "Seconds to wait before turning off after no motion/door activity"
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
      default: 300
    late_night_start:
      name: Late Night Start Time
      description: "Time to start using late night settings (e.g., '22:00')"
      selector:
        time:
    late_night_end:
      name: Late Night End Time
      description: "Time to end late night settings (e.g., '06:00')"
      selector:
        time:
    late_night_brightness:
      name: Late Night Brightness
      description: "Brightness level during late night hours (1-100)"
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
      default: 30
    late_night_wait:
      name: Late Night Turn Off Delay
      description: "Seconds to wait before turning off during late night hours"
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
      default: 120
    turn_on_transition:
      name: Turn On Transition
      description: "Transition time in seconds when turning on (ignored for scenes)"
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: seconds
      default: 1
    turn_off_transition:
      name: Turn Off Transition
      description: "Transition time in seconds when turning off (ignored for scenes)"
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: seconds
      default: 2

trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"
    id: "motion_on"
  - platform: state
    entity_id: !input motion_sensors
    to: "off"
    id: "motion_off"
  - platform: state
    entity_id: !input door_sensors
    to: "on"
    id: "door_on"
  - platform: state
    entity_id: !input door_sensors
    to: "off"
    id: "door_off"
  - platform: homeassistant
    event: start
    id: "ha_start"

variables:
  timer_name: "motion_light_timer"
  current_time: >-
    {{ now().strftime("%H:%M") }}
  is_late_night: >-
    {% set current = now().strftime("%H:%M") %}
    {% set start = input.late_night_start %}
    {% set end = input.late_night_end %}
    {% if start <= end %}
      {{ current >= start and current < end }}
    {% else %}
      {{ current >= start or current < end }}
    {% endif %}
  current_delay: >-
    {% if is_late_night %}
      {{ input.late_night_wait }}
    {% else %}
      {{ input.no_motion_wait }}
    {% endif %}
  is_motion_active: >-
    {% set motion_active = false %}
    {% for sensor in input.motion_sensors %}
      {% if states(sensor) == 'on' %}
        {% set motion_active = true %}
      {% endif %}
    {% endfor %}
    {{ motion_active }}
  is_door_active: >-
    {% set door_active = false %}
    {% if input.door_sensors %}
      {% for sensor in input.door_sensors %}
        {% if states(sensor) == 'on' %}
          {% set door_active = true %}
        {% endif %}
      {% endfor %}
    {% endif %}
    {{ door_active }}
  any_entity_on: >-
    {% set any_on = false %}
    {% for target in input.controlled_entities.entity_id %}
      {% if states(target) == 'on' %}
        {% set any_on = true %}
      {% endif %}
    {% endfor %}
    {{ any_on }}
  should_use_transition: >-
    {% set use_transition = true %}
    {% for target in input.controlled_entities.entity_id %}
      {% if target.split('.')[0] == 'scene' %}
        {% set use_transition = false %}
      {% endif %}
    {% endfor %}
    {{ use_transition }}

action:
  # Debug logging
  - if:
      - condition: template
        value_template: "{{ input.debug_mode }}"
    then:
      - service: system_log.write
        data:
          message: "Motion Light Debug - Trigger: {{ trigger.id }}, Motion Active: {{ is_motion_active }}, Door Active: {{ is_door_active }}, Late Night: {{ is_late_night }}"
          level: debug

  # Handle HA startup
  - if:
      - condition: trigger
        id: "ha_start"
      - condition: template
        value_template: >
          {% set override_state = states(input.override_input_boolean) %}
          {{ override_state == 'off' }}
      - condition: template
        value_template: "{{ not is_motion_active and not is_door_active }}"
    then:
      - service: homeassistant.turn_off
        target: !input controlled_entities
        data:
          transition: "{{ input.turn_off_transition if should_use_transition else 0 }}"

  # Check override state
  - condition: template
    value_template: >
      {% set override_state = states(input.override_input_boolean) %}
      {{ override_state == 'off' }}

  # Sun check
  - condition: or
    conditions:
      - condition: state
        entity_id: !input sun_entity
        state: "below_horizon"
      - condition: state
        entity_id: !input sun_entity
        state: "night"

  # Main action logic
  - choose:
      # Handle motion/door ON triggers
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: "motion_on"
              - condition: trigger
                id: "door_on"
          - condition: template
            value_template: "{{ not any_entity_on }}"
        sequence:
          - service: homeassistant.turn_on
            target: !input controlled_entities
            data:
              transition: "{{ input.turn_on_transition if should_use_transition else 0 }}"
              brightness_pct: "{{ input.late_night_brightness if is_late_night else 100 }}"

      # Handle motion OFF trigger
      - conditions:
          - condition: trigger
            id: "motion_off"
          - condition: template
            value_template: "{{ any_entity_on }}"
          # Only start timer if no door is active
          - condition: template
            value_template: "{{ not is_door_active }}"
        sequence:
          - delay:
              seconds: "{{ current_delay }}"
          # Double check nothing is active before turning off
          - condition: template
            value_template: "{{ not is_motion_active and not is_door_active }}"
          - service: homeassistant.turn_off
            target: !input controlled_entities
            data:
              transition: "{{ input.turn_off_transition if should_use_transition else 0 }}"

      # Handle door OFF trigger
      - conditions:
          - condition: trigger
            id: "door_off"
          - condition: template
            value_template: "{{ any_entity_on }}"
          # Only start timer if no motion is active
          - condition: template
            value_template: "{{ not is_motion_active }}"
        sequence:
          - delay:
              seconds: "{{ current_delay }}"
          # Double check nothing is active before turning off
          - condition: template
            value_template: "{{ not is_motion_active and not is_door_active }}"
          - service: homeassistant.turn_off
            target: !input controlled_entities
            data:
              transition: "{{ input.turn_off_transition if should_use_transition else 0 }}"
